# fly.toml app configuration file generated for lab3-iwis on 2024-02-20T17:00:51+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lab3-iwis'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'
  
[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'